global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['server:8000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

